# Generated by Django 6.0 on 2025-12-13 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, help_text='Comma-separated if multiple', max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='writer',
            field=models.CharField(blank=True, help_text='Comma-separated if multiple', max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='streaming_service',
            field=models.CharField(blank=True, choices=[('netflix', 'Netflix'), ('prime', 'Amazon Prime Video'), ('disney', 'Disney+'), ('hulu', 'Hulu'), ('max', 'Max (HBO)'), ('apple', 'Apple TV+'), ('paramount', 'Paramount+'), ('peacock', 'Peacock'), ('starz', 'Starz'), ('showtime', 'Showtime'), ('tubi', 'Tubi'), ('pluto', 'Pluto TV'), ('freevee', 'Amazon Freevee'), ('kanopy', 'Kanopy'), ('criterion', 'Criterion Channel'), ('other', 'Other / Physical Media')], max_length=50),
        ),
        migrations.AlterField(
            model_name='viewing',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Rating from 0–5 (half stars allowed)', max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
