# Generated by Django 6.0 on 2025-12-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, help_text='Upload a movie poster image', null=True, upload_to='posters/'),
        ),
    ]
