# Generated by Django 6.0 on 2025-12-13 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_movie_director_movie_writer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='viewing',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='movie',
            name='streaming_service',
        ),
        migrations.AlterField(
            model_name='viewing',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Rating from 0–5 (half-star increments allowed)', max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='movie',
            name='streaming_services',
            field=models.ManyToManyField(blank=True, related_name='movies', to='tracker.streamingservice'),
        ),
    ]
